### ISSUE TITLE
Incompatible flag running push

### ISSUE THREAD

**Issue by murbano83** [GoogleCloudPlatform/k8s-cloudkms-plugin#18]
Hello!

I cannot push to my project the image, i am getting this error when I run `bazel run cmd/plugin:push`

```bash
INFO: Writing tracer profile to '/private/var/tmp/_bazel_murbano/73b6f5ffed7a5444a1c9c28cf5208578/command.profile.gz'
ERROR: /private/var/tmp/_bazel_murbano/73b6f5ffed7a5444a1c9c28cf5208578/external/io_bazel_rules_go/BUILD.bazel:66:1: in go_context_data rule @io_bazel_rules_go//:go_con
text_data: 
Traceback (most recent call last):
        File "/private/var/tmp/_bazel_murbano/73b6f5ffed7a5444a1c9c28cf5208578/external/io_bazel_rules_go/BUILD.bazel", line 66
                go_context_data(name = 'go_context_data')
        File "/private/var/tmp/_bazel_murbano/73b6f5ffed7a5444a1c9c28cf5208578/external/io_bazel_rules_go/go/private/context.bzl", line 400, in _go_context_data_impl
                cc_common.configure_features(<3 more arguments>)
Incompatible flag --incompatible_require_ctx_in_configure_features has been flipped, and the mandatory parameter 'ctx' of cc_common.configure_features is missing. Please add 'ctx' as a named parameter. See https://github.com/bazelbuild/bazel/issues/7793 for details.
DEBUG: Rule 'distroless_static' indicated that a canonical reproducible form can be obtained by modifying arguments digest = "sha256:c6d5981545ce1406d33e61434c61e9452da
d93ecd8397c41e89036ef977a88f4"
DEBUG: Call stack for the definition of repository 'distroless_static' which is a container_pull (rule definition at /private/var/tmp/_bazel_murbano/73b6f5ffed7a5444a1c
9c28cf5208578/external/io_bazel_rules_docker/container/pull.bzl:173:18):
 - /Users/murbano/go/src/github.com/GoogleCloudPlatform/k8s-cloudkms-plugin/WORKSPACE:107:1
ERROR: Analysis of target '//cmd/plugin:push' failed; build aborted: Analysis of target '@io_bazel_rules_go//:go_context_data' failed; build aborted
INFO: Elapsed time: 0.560s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 31 targets configured)
FAILED: Build did NOT complete successfully (1 packages loaded, 31 targets configured)
```

 I am using last version of bazel 1.1.0.

**Comment by murbano83** [comment]
Using version Bazel 0.23.0 works.

```
brew install https://raw.githubusercontent.com/bazelbuild/homebrew-tap/85756b9147fa7ff9a139a0560acf7fc15750111c/Formula/bazel.rb
```

Also I had to remove `-static` tag on macos.

**Comment by sethvargo** [comment]
https://github.com/GoogleCloudPlatform/k8s-cloudkms-plugin/pull/20 moves away from bazel to make. You'll be able to use any of the make targets or pure docker commands to build and push.
